
---

kind:               Pod
apiVersion:         v1

metadata:   
    name:           pod-ivan
    
spec:
    volumes:
        - name: mivolumen
          emptyDir: 
            medium: Memory
        - name: mivolumen2
          hostPath:
            path: /home/ubuntu/environment/datos
            type: DirectoryOrCreate
        - name: mivolumen3
          persistentVolumeClaim:
            claimName:  mi-peticion
        - name: mivolumen4
          configMap: 
            name: otros-datos
    containers:
        - name:         contenedor1
          image:        nginx
          imagePullPolicy:   IfNotPresent
          volumeMounts:
            - name:     mivolumen
              mountPath: /datos

        - name:         contenedor2
          image:        fedora
          imagePullPolicy:   IfNotPresent
          command: 
            - tail 
            - -f 
            - /dev/null
          volumeMounts:
            - name:     mivolumen
              mountPath: /datosOtros
            - name:     mivolumen2
              mountPath: /datosOtros2
            - name:     mivolumen3
              mountPath: /datosOtros3
            - name:     mivolumen4
              mountPath: /datosOtros4
              # Kubernetes crea en la carpeta /datosOtros4
              # 2 ficheros:
              # dato1, cuyo contenido será valor1
              # nginx.conf, cuyo contenido será UN TOCHO!
          env:
                - name:         variable1
                  value:        valor1
                - name:         usuario-bd
                  valueFrom:        
                    configMapKeyRef:
                        name:   datos
                        key:    usuario
                - name:         password-bd
                  valueFrom:        
                    secretKeyRef:
                        name:   datos-secretos
                        key:    password
                - name:         nombre-bd
                  valueFrom:        
                    configMapKeyRef:
                        name:   datos
                        key:    basedatos
                  
              